@startuml
remove Form
remove Label
remove Button
remove TextBox
remove ComboBox
remove Guid
remove FlowLayoutPanel
remove Panel 
remove NumericUpDown
remove DateTimePicker
remove DateOnly 
remove TimeOnly 
remove ListView 
remove DataGridView
remove DateTime
remove ICollection`1
remove ListBox
remove AccessibleRole
remove Control 
remove ControlAccessibleObject
remove Color 
remove UserControl
remove List`1
remove Dictionary`2
remove IServiceProvider
remove @unlinked
!include .\\Decipher\Program.puml
!include .\\Decipher\Models\Alphabet.puml
!include .\\Decipher\Models\BestScores.puml
!include .\\Decipher\Models\Game.puml
!include .\\Decipher\Models\IRepository.puml
!include .\\Decipher\Models\Letter.puml
!include .\\Decipher\Models\Repository.puml
!include .\\Decipher\Models\User.puml
!include .\\Decipher\Models\UserError.puml
!include .\\Decipher\Models\WeakestLetter.puml
!include .\\Decipher\Presenter\AlphabetPresenter.puml
!include .\\Decipher\Presenter\MainPresenter.puml
!include .\\Decipher\Presenter\MenuPresenter.puml
!include .\\Decipher\Presenter\ProfilePresenter.puml
!include .\\Decipher\Presenter\QuizPresenter.puml
!include .\\Decipher\Presenter\ScorePresenter.puml
!include .\\Decipher\Presenter\StatsPresenter.puml
!include .\\Decipher\Properties\Resources.Designer.puml
!include .\\Decipher\View\AlphabetView.puml
!include .\\Decipher\View\AlphabetView.Designer.puml
!include .\\Decipher\View\IAlphabetView.puml
!include .\\Decipher\View\IMainView.puml
!include .\\Decipher\View\IMenuView.puml
!include .\\Decipher\View\IProfileView.puml
!include .\\Decipher\View\IQuizView.puml
!include .\\Decipher\View\IScoreView.puml
!include .\\Decipher\View\IStatsView.puml
!include .\\Decipher\View\MainView.puml
!include .\\Decipher\View\MainView.Designer.puml
!include .\\Decipher\View\MenuView.puml
!include .\\Decipher\View\MenuView.Designer.puml
!include .\\Decipher\View\ProfileView.puml
!include .\\Decipher\View\ProfileView.Designer.puml
!include .\\Decipher\View\QuizView.puml
!include .\\Decipher\View\QuizView.Designer.puml
!include .\\Decipher\View\ScoreView.puml
!include .\\Decipher\View\ScoreView.Designer.puml
!include .\\Decipher\View\StatsView.puml
!include .\\Decipher\View\StatsView.Designer.puml
!include .\\Decipher\obj\Debug\net90-windows\.NETCoreApp,Version=v9.0.AssemblyAttributes.puml
!include .\\Decipher\obj\Debug\net90-windows\Decipher.AssemblyInfo.puml
!include .\\Decipher\obj\Debug\net90-windows\Decipher.GlobalUsings.g.puml
@enduml
