@startuml
class ScoreView <<partial>> {
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
}
ScoreView --> "labGameOver" Label
ScoreView --> "labCurrent" Label
ScoreView --> "labBest" Label
ScoreView --> "btnPlayAgain" Button
ScoreView --> "btnMainMenu" Button
@enduml
