@startuml
class MainView <<partial>> {
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
}
MainView --> "stripMenu" MenuStrip
MainView --> "stripMain" ToolStripMenuItem
MainView --> "stripStats" ToolStripMenuItem
MainView --> "stripProfile" ToolStripMenuItem
MainView --> "panelMain" Panel
MainView --> "statusStrip1" StatusStrip
MainView --> "statusStatus" ToolStripStatusLabel
@enduml
