@startuml
class MenuView <<partial>> {
    +  <<event>> btnLanguageClicked : EventHandler? 
    +  <<event>> btnLetterClicked : EventHandler? 
    + MenuView()
}
UserControl <|-- MenuView
IMenuView <|-- MenuView
@enduml
